import { Language, TranslationMap, VoiceOption } from './types';

// TODO: Replace with your actual Google Cloud OAuth 2.0 Client ID
// Format: "1234567890-abcdefg.apps.googleusercontent.com"
export const GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID || "";

export const GOOGLE_SCOPES = [
  'https://www.googleapis.com/auth/drive.file',
  'https://www.googleapis.com/auth/documents',
  'https://www.googleapis.com/auth/classroom.courses.readonly',
  'https://www.googleapis.com/auth/classroom.coursework.me',
  'https://www.googleapis.com/auth/classroom.coursework.students',
  'https://www.googleapis.com/auth/userinfo.profile',
  'https://www.googleapis.com/auth/userinfo.email'
].join(' ');

if (!GOOGLE_CLIENT_ID) {
  console.warn("VITE_GOOGLE_CLIENT_ID가 설정되지 않았습니다. Google 로그인 기능이 제한될 수 있습니다.");
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'auto', name: '언어 자동 감지 (Auto)', flag: '✨' },
  { code: 'ko', name: '한국어 (Korean)', flag: '🇰🇷' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'ja', name: '日本語 (Japanese)', flag: '🇯🇵' },
  { code: 'zh', name: '中文 (Chinese)', flag: '🇨🇳' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'th', name: 'ภาษาไทย (Thai)', flag: '🇹🇭' },
  { code: 'id', name: 'Bahasa Indo', flag: '🇮🇩' },
  { code: 'ar', name: 'العربية (Arabic)', flag: '🇸🇦' },
  { code: 'hi', name: 'हिन्दी (Hindi)', flag: '🇮🇳' },
  { code: 'tl', name: 'Tagalog', flag: '🇵🇭' },
  { code: 'mn', name: 'Монгол (Mongolian)', flag: '🇲🇳' },
  { code: 'uz', name: 'Oʻzbek (Uzbek)', flag: '🇺🇿' },
];

export const GOOGLE_USER_STORAGE_KEY = 'google_user';
export const ACCESS_TOKEN_STORAGE_KEY = 'google_access_token';
export const SETTINGS_KEY = 'global_class_settings';
export const UI_LANG_KEY = 'global_class_ui_lang';
export const ADMIN_EMAIL = 'limonelist@gmail.com';
export const HISTORY_RENDER_STEP = 50;

export const VOICE_OPTIONS: VoiceOption[] = [
  { name: 'Kore', label: 'Kore', gender: 'Female', style: 'Calm' },
  { name: 'Puck', label: 'Puck', gender: 'Male', style: 'Deep' },
  { name: 'Charon', label: 'Charon', gender: 'Male', style: 'Authoritative' },
  { name: 'Fenrir', label: 'Fenrir', gender: 'Male', style: 'Resonant' },
  { name: 'Zephyr', label: 'Zephyr', gender: 'Female', style: 'Energetic' },
];

export const MODEL_LIVE = 'gemini-2.5-flash-native-audio-preview-09-2025';
export const MODEL_TRANSLATE = 'gemini-2.5-flash';
export const MODEL_VISION = 'gemini-2.5-flash';
export const MODEL_TTS = 'gemini-2.5-flash-preview-tts';

export const TRANSLATIONS: Record<string, TranslationMap> = {
  ko: {
    appTitle: "Global Class",
    subtitle: "실시간 AI 통역 노트",
    inputLang: "입력 언어",
    outputLang: "출력 언어",
    autoPlay: "자동 읽기",
    playAll: "전체 듣기",
    statusListening: "듣는 중...",
    statusStandby: "시작하려면 터치",
    connectionError: "연결 오류",
    retry: "재시도",
    connecting: "연결 중...",
    visionButton: "칠판 촬영",
    visionTitle: "칠판/노트 번역",
    visionDetected: "감지된 텍스트",
    visionTranslated: "번역 결과",
    visionRetake: "다시 찍기",
    visionAnalyzing: "분석 중...",
    visionNoText: "텍스트 없음",
    visionFail: "실패",
    visionError: "오류",
    voiceLabel: "목소리 설정",
    emptyHint: "마이크를 켜고 말씀을 시작하세요.\n실시간으로 적고 번역해 드립니다.",
    loadMoreHistory: "이전 내용 더 보기",
    exportMenu: "내보내기",
    exportDocs: "Google Docs 저장",
    exportDrive: "Google Drive 백업",
    exportClassroom: "Classroom 제출",
    exportNotebookLM: "NotebookLM용 소스 저장",
    loginRequired: "Google 로그인이 필요합니다.",
    loginRequiredDrive: "Drive 백업은 로그인이 필요합니다.",
    loginRequiredClassroom: "Classroom 제출은 로그인이 필요합니다.",
    loginUnavailable: "로그인 불가 (도메인 설정 확인)",
    offlineMode: "비로그인 상태: 텍스트 파일로 다운로드합니다.",
    exporting: "처리 중...",
    exportSuccess: "완료되었습니다!",
    selectCourse: "수업 선택",
    fetchingCourses: "수업 목록 불러오는 중...",
    noCourses: "참여 중인 수업이 없습니다.",
    submitTo: "제출하기",
    loginModalTitle: "로그인 방법 선택",
    loginGoogle: "Google로 로그인",
    loginGoogleDesc: "Classroom, Docs, Drive 기능을 사용합니다.",
    loginGuest: "게스트로 계속하기",
    loginGuestDesc: "기록을 기기에만 저장합니다.",
    copySuccess: "복사되었습니다.",
    noAudioToExport: "재생 가능한 오디오 데이터가 없습니다.",
    downloadCombinedAudio: "전체 음성 다운로드",
    autoScroll: "자동 스크롤",
    guideTitle: "빠른 안내",
    guideMic: "마이크 버튼을 눌러 실시간 번역을 시작하세요.",
    guideDrive: "Google 로그인 시 Drive 백업/Docs 저장 가능.",
    guideVision: "칠판 촬영(비전)으로 텍스트 감지 번역 가능.",
    guideAuto: "자동 읽기/스크롤 토글로 편의 기능 선택.",
    shortcutTitle: "단축키",
    shortcutSpace: "스페이스: 마이크 on/off",
    mobileTipTitle: "모바일 팁",
    mobileTipDesc: "하단 고정 버튼으로 한 손 조작, 세로 모드 최적화",
  },
  en: {
    appTitle: "Global Class",
    subtitle: "AI Live Interpreter",
    inputLang: "Input",
    outputLang: "Output",
    autoPlay: "Auto Read",
    playAll: "Play All",
    statusListening: "Listening...",
    statusStandby: "Tap to Start",
    connectionError: "Error",
    retry: "Retry",
    connecting: "Connecting...",
    visionButton: "Vision",
    visionTitle: "Board Translation",
    visionDetected: "Detected",
    visionTranslated: "Translation",
    visionRetake: "Retake",
    visionAnalyzing: "Analyzing...",
    visionNoText: "No text",
    visionFail: "Failed",
    visionError: "Error",
    voiceLabel: "Voice",
    emptyHint: "Turn on the mic and start speaking.\nWe will transcribe and translate in real-time.",
    loadMoreHistory: "Load earlier messages",
    exportMenu: "Export",
    exportDocs: "Save to Google Docs",
    exportDrive: "Backup to Drive",
    exportClassroom: "Submit to Classroom",
    exportNotebookLM: "Save for NotebookLM",
    loginRequired: "Google Login Required",
    loginRequiredDrive: "Login required for Drive backup.",
    loginRequiredClassroom: "Login required for Classroom submission.",
    loginUnavailable: "Login Unavailable (Domain Error)",
    offlineMode: "Logged out: Downloading as text file.",
    exporting: "Processing...",
    exportSuccess: "Done!",
    selectCourse: "Select Class",
    fetchingCourses: "Fetching classes...",
    noCourses: "No classes found.",
    submitTo: "Submit",
    loginModalTitle: "Choose Login Method",
    loginGoogle: "Sign in with Google",
    loginGoogleDesc: "Enable Classroom, Docs, and Drive features.",
    loginGuest: "Continue as Guest",
    loginGuestDesc: "Save transcripts locally only.",
    copySuccess: "Copied to clipboard.",
    noAudioToExport: "No playable audio data found.",
    downloadCombinedAudio: "Download All Audio",
    autoScroll: "Auto Scroll",
    guideTitle: "Quick Guide",
    guideMic: "Press the mic button to start real-time translation.",
    guideDrive: "Drive backup and Docs saving available with Google login.",
    guideVision: "Capture boards (Vision) for OCR and translation.",
    guideAuto: "Toggle auto-play and auto-scroll for convenience.",
    shortcutTitle: "Shortcuts",
    shortcutSpace: "Space: Mic on/off",
    mobileTipTitle: "Mobile Tip",
    mobileTipDesc: "Optimized for one-handed operation and portrait mode.",
  },
  ja: {
    appTitle: "グローバル教室",
    subtitle: "AIリアルタイム通訳",
    inputLang: "入力",
    outputLang: "出力",
    autoPlay: "自動再生",
    playAll: "全再生",
    statusListening: "聞き取り中...",
    statusStandby: "タッチして開始",
    connectionError: "エラー",
    retry: "再試行",
    connecting: "接続中...",
    visionButton: "撮影",
    visionTitle: "黒板翻訳",
    visionDetected: "検出",
    visionTranslated: "翻訳",
    visionRetake: "再撮影",
    visionAnalyzing: "分析中...",
    visionNoText: "テキストなし",
    visionFail: "失敗",
    visionError: "エラー",
    voiceLabel: "音声",
    emptyHint: "マイクをオンにして話し始めてください。\nリアルタイムで書き起こして翻訳します。",
    loadMoreHistory: "以前の内容をもっと見る",
    exportMenu: "エクスポート",
    exportDocs: "Google Docsに保存",
    exportDrive: "Driveにバックアップ",
    exportClassroom: "Classroomに提出",
    exportNotebookLM: "NotebookLM用ソース保存",
    loginRequired: "Googleログインが必要です",
    loginRequiredDrive: "Drive機能はログインが必要です",
    loginRequiredClassroom: "Classroom機能はログインが必要です",
    loginUnavailable: "ログイン不可 (ドメイン設定)",
    offlineMode: "未ログイン：テキストファイルとして保存します。",
    exporting: "処理中...",
    exportSuccess: "完了しました！",
    selectCourse: "クラスを選択",
    fetchingCourses: "クラスを取得中...",
    noCourses: "クラスが見つかりません。",
    submitTo: "提出",
    loginModalTitle: "ログイン方法の選択",
    loginGoogle: "Googleでログイン",
    loginGoogleDesc: "Classroom, Docs, Drive機能を使用します。",
    loginGuest: "ゲストとして続行",
    loginGuestDesc: "履歴をデバイスにのみ保存합니다.",
    copySuccess: "コピーされました。",
    noAudioToExport: "再生可能なオー디오データがありません。",
    downloadCombinedAudio: "音声を一括ダウンロード",
    autoScroll: "自動スクロール",
    guideTitle: "クイックガイド",
    guideMic: "マイクボタンを押してリアルタイム通訳を開始します。",
    guideDrive: "GoogleログインでDriveバックアップとDocs保存が可能。",
    guideVision: "黒板撮影（ビジョン）でOCRと翻訳が可能。",
    guideAuto: "自動再生と自動スクロールを切り替えて便利に。",
    shortcutTitle: "ショートカット",
    shortcutSpace: "スペース: マイクのオン/オフ",
    mobileTipTitle: "モバイルのヒント",
    mobileTipDesc: "片手操作と縦向きモードに最適化されています。",
  },
  zh: {
    appTitle: "全球课堂",
    subtitle: "AI 实时翻译",
    inputLang: "输入",
    outputLang: "输出",
    autoPlay: "自动朗读",
    playAll: "全部播放",
    statusListening: "聆听中...",
    statusStandby: "点击开始",
    connectionError: "错误",
    retry: "重试",
    connecting: "连接中...",
    visionButton: "拍照",
    visionTitle: "黑板翻译",
    visionDetected: "检测",
    visionTranslated: "翻译",
    visionRetake: "重拍",
    visionAnalyzing: "分析中...",
    visionNoText: "无文本",
    visionFail: "失败",
    visionError: "错误",
    voiceLabel: "声音",
    emptyHint: "打开麦克风并开始说话。\n我们将实时转录并翻译。",
    loadMoreHistory: "查看更多历史",
    exportMenu: "导出",
    exportDocs: "保存到 Google Docs",
    exportDrive: "备份到 Drive",
    exportClassroom: "提交到 Classroom",
    exportNotebookLM: "保存到 NotebookLM",
    loginRequired: "需要 Google 登录",
    loginRequiredDrive: "Drive 功能需要登录",
    loginRequiredClassroom: "Classroom 功能需要登录",
    loginUnavailable: "无法登录 (域错误)",
    offlineMode: "未登录：下载为文本文件。",
    exporting: "处理中...",
    exportSuccess: "完成！",
    selectCourse: "选择课程",
    fetchingCourses: "正在获取课程...",
    noCourses: "未找到课程。",
    submitTo: "提交",
    loginModalTitle: "选择登录方式",
    loginGoogle: "使用 Google 登录",
    loginGoogleDesc: "使用 Classroom、Docs 和 Drive 功能。",
    loginGuest: "以访客身份继续",
    loginGuestDesc: "仅将记录保存在本地。",
    copySuccess: "已复制到剪贴板。",
    noAudioToExport: "未找到可播放的音频数据。",
    downloadCombinedAudio: "下载合并音频",
    autoScroll: "自动滚动",
    guideTitle: "快速指南",
    guideMic: "点击麦克风按钮开始实时翻译。",
    guideDrive: "使用 Google 登录可进行 Drive 备份和 Docs 保存。",
    guideVision: "拍摄黑板（视觉）进行文字识别和翻译。",
    guideAuto: "切换自动朗读和自动滚动以获得便利。",
    shortcutTitle: "快捷键",
    shortcutSpace: "空格：麦克风 开/关",
    mobileTipTitle: "移动端技巧",
    mobileTipDesc: "针对单手操作和竖屏模式进行了优化。",
  },
  vi: {
    appTitle: "Lớp Học Toàn Cầu",
    subtitle: "Phiên dịch AI",
    inputLang: "Đầu vào",
    outputLang: "Đầu ra",
    autoPlay: "Tự động đọc",
    playAll: "Nghe tất cả",
    statusListening: "Đang nghe...",
    statusStandby: "Chạm để bắt đầu",
    connectionError: "Lỗi",
    retry: "Thử lại",
    connecting: "Đang kết nối...",
    visionButton: "Chụp ảnh",
    visionTitle: "Dịch bảng",
    visionDetected: "Đã phát hiện",
    visionTranslated: "Bản dịch",
    visionRetake: "Chụp lại",
    visionAnalyzing: "Đang phân tích...",
    visionNoText: "Không có chữ",
    visionFail: "Thất bại",
    visionError: "Lỗi",
    voiceLabel: "Giọng",
    emptyHint: "Bật micrô và bắt đầu nói.\nChúng tôi sẽ ghi chép và dịch theo thời gian thực.",
    loadMoreHistory: "Xem thêm lịch sử",
    exportMenu: "Xuất",
    exportDocs: "Lưu vào Google Docs",
    exportDrive: "Sao lưu vào Drive",
    exportClassroom: "Nộp lên Classroom",
    exportNotebookLM: "Lưu cho NotebookLM",
    loginRequired: "Cần đăng nhập Google",
    loginRequiredDrive: "Cần đăng nhập để dùng Drive",
    loginRequiredClassroom: "Cần đăng nhập để nộp Classroom",
    loginUnavailable: "Đăng nhập không khả dụng (Lỗi tên miền)",
    offlineMode: "Chưa đăng nhập: Tải xuống tệp văn bản.",
    exporting: "Đang xử lý...",
    exportSuccess: "Hoàn tất!",
    selectCourse: "Chọn lớp học",
    fetchingCourses: "Đang tải danh sách lớp...",
    noCourses: "Không tìm thấy lớp học.",
    submitTo: "Nộp",
    loginModalTitle: "Chọn phương thức đăng nhập",
    loginGoogle: "Đăng nhập bằng Google",
    loginGoogleDesc: "Sử dụng tính năng Classroom, Docs, Drive.",
    loginGuest: "Tiếp tục với tư cách Khách",
    loginGuestDesc: "Chỉ lưu lịch sử trên thiết bị này.",
    copySuccess: "Đã sao chép vào bộ nhớ tạm.",
    noAudioToExport: "Không tìm thấy dữ liệu âm thanh để phát.",
    downloadCombinedAudio: "Tải xuống âm thanh hợp nhất",
    autoScroll: "Tự động cuộn",
    guideTitle: "Hướng dẫn nhanh",
    guideMic: "Nhấn nút micrô để bắt đầu phiên dịch thời gian thực.",
    guideDrive: "Có thể sao lưu Drive/lưu Docs khi đăng nhập Google.",
    guideVision: "Chụp bảng (Vision) để nhận diện văn bản và dịch.",
    guideAuto: "Bật/tắt tự động đọc/cuộn để thuận tiện hơn.",
    shortcutTitle: "Phím tắt",
    shortcutSpace: "Space: Bật/tắt micrô",
    mobileTipTitle: "Mẹo di động",
    mobileTipDesc: "Tối ưu cho thao tác một tay, chế độ chân dung.",
  },
  es: {
    appTitle: "Clase Global",
    subtitle: "Intérprete IA",
    inputLang: "Entrada",
    outputLang: "Salida",
    autoPlay: "Auto Leer",
    playAll: "Reprod. Todo",
    statusListening: "Escuchando...",
    statusStandby: "Toque para iniciar",
    connectionError: "Error",
    retry: "Reintentar",
    connecting: "Conectando...",
    visionButton: "Cámara",
    visionTitle: "Traducción",
    visionDetected: "Detectado",
    visionTranslated: "Traducción",
    visionRetake: "Retomar",
    visionAnalyzing: "Analizando...",
    visionNoText: "Sin texto",
    visionFail: "Fallido",
    visionError: "Error",
    voiceLabel: "Voz",
    emptyHint: "Enciende el micrófono y empieza a hablar.\nTranscribiremos y traduciremos en tiempo real.",
    loadMoreHistory: "Ver mensajes anteriores",
    exportMenu: "Exportar",
    exportDocs: "Guardar en Google Docs",
    exportDrive: "Respaldo en Drive",
    exportClassroom: "Enviar a Classroom",
    exportNotebookLM: "Guardar para NotebookLM",
    loginRequired: "Requiere Google Login",
    loginRequiredDrive: "Login requerido para Drive",
    loginRequiredClassroom: "Login requerido para Classroom",
    loginUnavailable: "Login no disponible (Error de dominio)",
    offlineMode: "No logueado: Descargando archivo de texto.",
    exporting: "Procesando...",
    exportSuccess: "¡Hecho!",
    selectCourse: "Seleccionar clase",
    fetchingCourses: "Obteniendo clases...",
    noCourses: "No se encontraron clases.",
    submitTo: "Enviar",
    loginModalTitle: "Elegir método de inicio",
    loginGoogle: "Iniciar con Google",
    loginGoogleDesc: "Usar funciones de Classroom, Docs y Drive.",
    loginGuest: "Continuar como invitado",
    loginGuestDesc: "Guardar historial solo localmente.",
    copySuccess: "Copiado al portapapeles.",
    noAudioToExport: "No se encontraron datos de audio reproducibles.",
    downloadCombinedAudio: "Descargar audio combinado",
    autoScroll: "Auto Scroll",
    guideTitle: "Guía rápida",
    guideMic: "Pulsa el botón del micro para iniciar la traducción.",
    guideDrive: "Respaldo en Drive y guardado en Docs con Google Login.",
    guideVision: "Captura pizarras (Vision) para OCR y traducción.",
    guideAuto: "Alterna auto-reproducción y auto-desplazamiento.",
    shortcutTitle: "Atajos",
    shortcutSpace: "Espacio: Micro on/off",
    mobileTipTitle: "Tip móvil",
    mobileTipDesc: "Optimizado para uso con una mano y modo vertical.",
  },
  fr: {
    appTitle: "Classe Mondiale",
    subtitle: "Interprète AI Live",
    inputLang: "Entrée",
    outputLang: "Sortie",
    autoPlay: "Lecture Auto",
    playAll: "Tout Lire",
    statusListening: "Écoute...",
    statusStandby: "Toucher pour démarrer",
    connectionError: "Erreur",
    retry: "Réessayer",
    connecting: "Connexion...",
    visionButton: "Caméra",
    visionTitle: "Traduction du Tableau",
    visionDetected: "Détecté",
    visionTranslated: "Traduction",
    visionRetake: "Reprendre",
    visionAnalyzing: "Analyse...",
    visionNoText: "Pas de texte",
    visionFail: "Échec",
    visionError: "Erreur",
    voiceLabel: "Voix",
    emptyHint: "Allumez le micro et commencez à parler.\nNous transcrirons et traduirons en temps réel.",
    loadMoreHistory: "Charger plus d'historique",
    exportMenu: "Exporter",
    exportDocs: "Enregistrer dans Google Docs",
    exportDrive: "Sauvegarde sur Drive",
    exportClassroom: "Soumettre à Classroom",
    exportNotebookLM: "Sauvegarder pour NotebookLM",
    loginRequired: "Connexion Google Requise",
    loginRequiredDrive: "Connexion requise pour Drive.",
    loginRequiredClassroom: "Connexion requise pour Classroom.",
    loginUnavailable: "Connexion impossible (Erreur de domaine)",
    offlineMode: "Déconnecté : téléchargement en fichier texte.",
    exporting: "Traitement...",
    exportSuccess: "Terminé !",
    selectCourse: "Choisir un cours",
    fetchingCourses: "Récupération des cours...",
    noCourses: "Aucun cours trouvé.",
    submitTo: "Soumettre",
    loginModalTitle: "Choisir la méthode de connexion",
    loginGoogle: "Se connecter avec Google",
    loginGoogleDesc: "Utiliser Classroom, Docs et Drive.",
    loginGuest: "Continuer en tant qu'invité",
    loginGuestDesc: "Enregistrer localement uniquement.",
    copySuccess: "Copié dans le presse-papiers.",
    noAudioToExport: "Aucune donnée audio à lire.",
    downloadCombinedAudio: "Télécharger tout l'audio",
    autoScroll: "Défilement Auto",
    guideTitle: "Guide Rapide",
    guideMic: "Appuyez sur le micro pour démarrer la traduction.",
    guideDrive: "Sauvegarde Drive et Docs disponible avec Google Login.",
    guideVision: "Utilisez la caméra pour OCR et traduction.",
    guideAuto: "Activez lecture/défilement auto.",
    shortcutTitle: "Raccourcis",
    shortcutSpace: "Espace : Micro on/off",
    mobileTipTitle: "Conseil Mobile",
    mobileTipDesc: "Optimisé pour une utilisation à une main.",
  },
  de: {
    appTitle: "Globale Klasse",
    subtitle: "KI-Live-Dolmetscher",
    inputLang: "Eingang",
    outputLang: "Ausgang",
    autoPlay: "Auto-Wiedergabe",
    playAll: "Alles abspielen",
    statusListening: "Zuhören...",
    statusStandby: "Tippen zum Starten",
    connectionError: "Fehler",
    retry: "Wiederholen",
    connecting: "Verbinde...",
    visionButton: "Kamera",
    visionTitle: "Tafelübersetzung",
    visionDetected: "Erkannt",
    visionTranslated: "Übersetzung",
    visionRetake: "Neu aufnehmen",
    visionAnalyzing: "Analysiere...",
    visionNoText: "Kein Text",
    visionFail: "Fehlgeschlagen",
    visionError: "Fehler",
    voiceLabel: "Stimme",
    emptyHint: "Mikro an und sprechen.\nWir transkribieren und übersetzen in Echtzeit.",
    loadMoreHistory: "Mehr Verlauf laden",
    exportMenu: "Exportieren",
    exportDocs: "In Google Docs speichern",
    exportDrive: "Drive-Backup",
    exportClassroom: "In Classroom abgeben",
    exportNotebookLM: "Für NotebookLM speichern",
    loginRequired: "Google Login erforderlich",
    loginRequiredDrive: "Login für Drive erforderlich.",
    loginRequiredClassroom: "Login für Classroom erforderlich.",
    loginUnavailable: "Login nicht möglich (Domain-Fehler)",
    offlineMode: "Abgemeldet: Download als Textdatei.",
    exporting: "Verarbeite...",
    exportSuccess: "Fertig!",
    selectCourse: "Kurs wählen",
    fetchingCourses: "Lade Kurse...",
    noCourses: "Keine Kurse gefunden.",
    submitTo: "Abgeben",
    loginModalTitle: "Anmeldemethode wählen",
    loginGoogle: "Mit Google anmelden",
    loginGoogleDesc: "Classroom, Docs und Drive nutzen.",
    loginGuest: "Als Gast fortfahren",
    loginGuestDesc: "Verlauf nur lokal speichern.",
    copySuccess: "Kopiert.",
    noAudioToExport: "Keine Audiodateien gefunden.",
    downloadCombinedAudio: "Alles herunterladen",
    autoScroll: "Auto-Scroll",
    guideTitle: "Kurzanleitung",
    guideMic: "Mikro drücken für Echtzeit-Übersetzung.",
    guideDrive: "Drive-Backup und Docs-Speicherung mit Login.",
    guideVision: "Tafel fotografieren für OCR & Übersetzung.",
    guideAuto: "Auto-Wiedergabe & Scrollen umschalten.",
    shortcutTitle: "Shortcuts",
    shortcutSpace: "Leertaste: Mikro an/aus",
    mobileTipTitle: "Mobil-Tipp",
    mobileTipDesc: "Optimiert für einhändige Bedienung.",
  },
  ru: {
    appTitle: "Глобальный класс",
    subtitle: "Живой AI переводчик",
    inputLang: "Ввод",
    outputLang: "Вывод",
    autoPlay: "Авточтение",
    playAll: "Играть все",
    statusListening: "Слушаю...",
    statusStandby: "Нажмите, чтобы начать",
    connectionError: "Ошибка",
    retry: "Повторить",
    connecting: "Подключение...",
    visionButton: "Камера",
    visionTitle: "Перевод доски",
    visionDetected: "Обнаружено",
    visionTranslated: "Перевод",
    visionRetake: "Переснять",
    visionAnalyzing: "Анализ...",
    visionNoText: "Нет текста",
    visionFail: "Ошибка",
    visionError: "Ошибка",
    voiceLabel: "Голос",
    emptyHint: "Включите микрофон и начните говорить.\nМы переведем в реальном времени.",
    loadMoreHistory: "Загрузить больше",
    exportMenu: "Экспорт",
    exportDocs: "Сохранить в Google Docs",
    exportDrive: "Бэкап на Drive",
    exportClassroom: "Сдать в Classroom",
    exportNotebookLM: "Для NotebookLM",
    loginRequired: "Нужен Google Login",
    loginRequiredDrive: "Нужен вход для Drive.",
    loginRequiredClassroom: "Нужен вход для Classroom.",
    loginUnavailable: "Вход недоступен",
    offlineMode: "Выход: загрузка в текстовый файл.",
    exporting: "Обработка...",
    exportSuccess: "Готово!",
    selectCourse: "Выбрать курс",
    fetchingCourses: "Загрузка курсов...",
    noCourses: "Курсы не найдены.",
    submitTo: "Сдать",
    loginModalTitle: "Выберите способ входа",
    loginGoogle: "Войти через Google",
    loginGoogleDesc: "Использовать Classroom, Docs и Drive.",
    loginGuest: "Как гость",
    loginGuestDesc: "Сохранять только локально.",
    copySuccess: "Скопировано.",
    noAudioToExport: "Нет аудио для загрузки.",
    downloadCombinedAudio: "Скачать всё аудио",
    autoScroll: "Автоскролл",
    guideTitle: "Руководство",
    guideMic: "Нажмите микро для перевода.",
    guideDrive: "Бэкап на Drive после входа.",
    guideVision: "Снимайте доски для OCR и перевода.",
    guideAuto: "Тумблеры авточтения и скролла.",
    shortcutTitle: "Клавиши",
    shortcutSpace: "Пробел: Микро вкл/выкл",
    mobileTipTitle: "Совет для мобильных",
    mobileTipDesc: "Оптимизировано для одной руки.",
  },
};

const DEFAULT_TRANS = TRANSLATIONS['en'];
['th', 'id', 'ar', 'hi', 'tl', 'mn', 'uz'].forEach(code => {
  if (!TRANSLATIONS[code]) TRANSLATIONS[code] = DEFAULT_TRANS;
});