import { Language, TranslationMap, VoiceOption } from './types';

// TODO: Replace with your actual Google Cloud OAuth 2.0 Client ID
// Format: "1234567890-abcdefg.apps.googleusercontent.com"
export const GOOGLE_CLIENT_ID = "322060753872-placeholder-client-id.apps.googleusercontent.com"; 

export const GOOGLE_SCOPES = [
  'https://www.googleapis.com/auth/drive.file',
  'https://www.googleapis.com/auth/documents',
  'https://www.googleapis.com/auth/classroom.courses.readonly',
  'https://www.googleapis.com/auth/classroom.coursework.me',
  'https://www.googleapis.com/auth/classroom.coursework.students',
  'https://www.googleapis.com/auth/userinfo.profile',
  'https://www.googleapis.com/auth/userinfo.email'
].join(' ');

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'ko', name: '한국어 (Korean)', flag: '🇰🇷' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'ja', name: '日本語 (Japanese)', flag: '🇯🇵' },
  { code: 'zh', name: '中文 (Chinese)', flag: '🇨🇳' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'th', name: 'ภาษาไทย (Thai)', flag: '🇹🇭' },
  { code: 'id', name: 'Bahasa Indo', flag: '🇮🇩' },
  { code: 'ar', name: 'العربية (Arabic)', flag: '🇸🇦' },
  { code: 'hi', name: 'हिन्दी (Hindi)', flag: '🇮🇳' },
  { code: 'tl', name: 'Tagalog', flag: '🇵🇭' },
  { code: 'mn', name: 'Монгол (Mongolian)', flag: '🇲🇳' },
  { code: 'uz', name: 'Oʻzbek (Uzbek)', flag: '🇺🇿' },
];

export const VOICE_OPTIONS: VoiceOption[] = [
  { name: 'Kore', label: 'Kore', gender: 'Female', style: 'Calm' },
  { name: 'Puck', label: 'Puck', gender: 'Male', style: 'Deep' },
  { name: 'Charon', label: 'Charon', gender: 'Male', style: 'Authoritative' },
  { name: 'Fenrir', label: 'Fenrir', gender: 'Male', style: 'Resonant' },
  { name: 'Zephyr', label: 'Zephyr', gender: 'Female', style: 'Energetic' },
];

export const MODEL_LIVE = 'gemini-2.5-flash-native-audio-preview-09-2025';
export const MODEL_TRANSLATE = 'gemini-2.5-flash'; 
export const MODEL_VISION = 'gemini-2.5-flash'; 
export const MODEL_TTS = 'gemini-2.5-flash-preview-tts';

export const TRANSLATIONS: Record<string, TranslationMap> = {
  ko: {
    appTitle: "Global Class",
    subtitle: "실시간 AI 통역 노트",
    inputLang: "입력 언어",
    outputLang: "출력 언어",
    autoPlay: "자동 읽기",
    playAll: "전체 듣기",
    statusListening: "듣는 중...",
    statusStandby: "시작하려면 터치",
    connectionError: "연결 오류",
    retry: "재시도",
    connecting: "연결 중...",
    visionButton: "칠판 촬영",
    visionTitle: "칠판/노트 번역",
    visionDetected: "감지된 텍스트",
    visionTranslated: "번역 결과",
    visionRetake: "다시 찍기",
    visionAnalyzing: "분석 중...",
    visionNoText: "텍스트 없음",
    visionFail: "실패",
    visionError: "오류",
    voiceLabel: "목소리 설정",
    emptyHint: "마이크를 켜고 말씀을 시작하세요.\n실시간으로 적고 번역해 드립니다.",
    exportMenu: "내보내기",
    exportDocs: "Google Docs 저장",
    exportDrive: "Google Drive 백업",
    exportClassroom: "Classroom 제출",
    loginRequired: "Google 로그인이 필요합니다.",
    loginRequiredDrive: "Drive 백업은 로그인이 필요합니다.",
    loginRequiredClassroom: "Classroom 제출은 로그인이 필요합니다.",
    loginUnavailable: "로그인 불가 (도메인 설정 확인)",
    offlineMode: "비로그인 상태: 텍스트 파일로 다운로드합니다.",
    exporting: "처리 중...",
    exportSuccess: "완료되었습니다!",
    selectCourse: "수업 선택",
    fetchingCourses: "수업 목록 불러오는 중...",
    noCourses: "참여 중인 수업이 없습니다.",
    submitTo: "제출하기",
    loginModalTitle: "로그인 방법 선택",
    loginGoogle: "Google로 로그인",
    loginGoogleDesc: "Classroom, Docs, Drive 기능을 사용합니다.",
    loginGuest: "게스트로 계속하기",
    loginGuestDesc: "기록을 기기에만 저장합니다.",
  },
  en: {
    appTitle: "Global Class",
    subtitle: "AI Live Interpreter",
    inputLang: "Input",
    outputLang: "Output",
    autoPlay: "Auto Read",
    playAll: "Play All",
    statusListening: "Listening...",
    statusStandby: "Tap to Start",
    connectionError: "Error",
    retry: "Retry",
    connecting: "Connecting...",
    visionButton: "Vision",
    visionTitle: "Board Translation",
    visionDetected: "Detected",
    visionTranslated: "Translation",
    visionRetake: "Retake",
    visionAnalyzing: "Analyzing...",
    visionNoText: "No text",
    visionFail: "Failed",
    visionError: "Error",
    voiceLabel: "Voice",
    emptyHint: "Turn on the mic and start speaking.\nWe will transcribe and translate in real-time.",
    exportMenu: "Export",
    exportDocs: "Save to Google Docs",
    exportDrive: "Backup to Drive",
    exportClassroom: "Submit to Classroom",
    loginRequired: "Google Login Required",
    loginRequiredDrive: "Login required for Drive backup.",
    loginRequiredClassroom: "Login required for Classroom submission.",
    loginUnavailable: "Login Unavailable (Domain Error)",
    offlineMode: "Logged out: Downloading as text file.",
    exporting: "Processing...",
    exportSuccess: "Done!",
    selectCourse: "Select Class",
    fetchingCourses: "Fetching classes...",
    noCourses: "No classes found.",
    submitTo: "Submit",
    loginModalTitle: "Choose Login Method",
    loginGoogle: "Sign in with Google",
    loginGoogleDesc: "Enable Classroom, Docs, and Drive features.",
    loginGuest: "Continue as Guest",
    loginGuestDesc: "Save transcripts locally only.",
  },
  ja: {
    appTitle: "グローバル教室",
    subtitle: "AIリアルタイム通訳",
    inputLang: "入力",
    outputLang: "出力",
    autoPlay: "自動再生",
    playAll: "全再生",
    statusListening: "聞き取り中...",
    statusStandby: "タッチして開始",
    connectionError: "エラー",
    retry: "再試行",
    connecting: "接続中...",
    visionButton: "撮影",
    visionTitle: "黒板翻訳",
    visionDetected: "検出",
    visionTranslated: "翻訳",
    visionRetake: "再撮影",
    visionAnalyzing: "分析中...",
    visionNoText: "テキストなし",
    visionFail: "失敗",
    visionError: "エラー",
    voiceLabel: "音声",
    emptyHint: "マイクをオンにして話し始めてください。\nリアルタイムで書き起こして翻訳します。",
    exportMenu: "エクスポート",
    exportDocs: "Google Docsに保存",
    exportDrive: "Driveにバックアップ",
    exportClassroom: "Classroomに提出",
    loginRequired: "Googleログインが必要です",
    loginRequiredDrive: "Drive機能はログインが必要です",
    loginRequiredClassroom: "Classroom機能はログインが必要です",
    loginUnavailable: "ログイン不可 (ドメイン設定)",
    offlineMode: "未ログイン：テキストファイルとして保存します。",
    exporting: "処理中...",
    exportSuccess: "完了しました！",
    selectCourse: "クラスを選択",
    fetchingCourses: "クラスを取得中...",
    noCourses: "クラスが見つかりません。",
    submitTo: "提出",
    loginModalTitle: "ログイン方法の選択",
    loginGoogle: "Googleでログイン",
    loginGoogleDesc: "Classroom, Docs, Drive機能を使用します。",
    loginGuest: "ゲストとして続行",
    loginGuestDesc: "履歴をデバイスにのみ保存します。",
  },
  zh: {
    appTitle: "全球课堂",
    subtitle: "AI 实时翻译",
    inputLang: "输入",
    outputLang: "输出",
    autoPlay: "自动朗读",
    playAll: "全部播放",
    statusListening: "聆听中...",
    statusStandby: "点击开始",
    connectionError: "错误",
    retry: "重试",
    connecting: "连接中...",
    visionButton: "拍照",
    visionTitle: "黑板翻译",
    visionDetected: "检测",
    visionTranslated: "翻译",
    visionRetake: "重拍",
    visionAnalyzing: "分析中...",
    visionNoText: "无文本",
    visionFail: "失败",
    visionError: "错误",
    voiceLabel: "声音",
    emptyHint: "打开麦克风并开始说话。\n我们将实时转录并翻译。",
    exportMenu: "导出",
    exportDocs: "保存到 Google Docs",
    exportDrive: "备份到 Drive",
    exportClassroom: "提交到 Classroom",
    loginRequired: "需要 Google 登录",
    loginRequiredDrive: "Drive 功能需要登录",
    loginRequiredClassroom: "Classroom 功能需要登录",
    loginUnavailable: "无法登录 (域错误)",
    offlineMode: "未登录：下载为文本文件。",
    exporting: "处理中...",
    exportSuccess: "完成！",
    selectCourse: "选择课程",
    fetchingCourses: "正在获取课程...",
    noCourses: "未找到课程。",
    submitTo: "提交",
    loginModalTitle: "选择登录方式",
    loginGoogle: "使用 Google 登录",
    loginGoogleDesc: "使用 Classroom、Docs 和 Drive 功能。",
    loginGuest: "以访客身份继续",
    loginGuestDesc: "仅将记录保存在本地。",
  },
  vi: {
    appTitle: "Lớp Học Toàn Cầu",
    subtitle: "Phiên dịch AI",
    inputLang: "Đầu vào",
    outputLang: "Đầu ra",
    autoPlay: "Tự động đọc",
    playAll: "Nghe tất cả",
    statusListening: "Đang nghe...",
    statusStandby: "Chạm để bắt đầu",
    connectionError: "Lỗi",
    retry: "Thử lại",
    connecting: "Đang kết nối...",
    visionButton: "Chụp ảnh",
    visionTitle: "Dịch bảng",
    visionDetected: "Đã phát hiện",
    visionTranslated: "Bản dịch",
    visionRetake: "Chụp lại",
    visionAnalyzing: "Đang phân tích...",
    visionNoText: "Không có chữ",
    visionFail: "Thất bại",
    visionError: "Lỗi",
    voiceLabel: "Giọng",
    emptyHint: "Bật micrô và bắt đầu nói.\nChúng tôi sẽ ghi chép và dịch theo thời gian thực.",
    exportMenu: "Xuất",
    exportDocs: "Lưu vào Google Docs",
    exportDrive: "Sao lưu vào Drive",
    exportClassroom: "Nộp lên Classroom",
    loginRequired: "Cần đăng nhập Google",
    loginRequiredDrive: "Cần đăng nhập để dùng Drive",
    loginRequiredClassroom: "Cần đăng nhập để nộp Classroom",
    loginUnavailable: "Đăng nhập không khả dụng (Lỗi tên miền)",
    offlineMode: "Chưa đăng nhập: Tải xuống tệp văn bản.",
    exporting: "Đang xử lý...",
    exportSuccess: "Hoàn tất!",
    selectCourse: "Chọn lớp học",
    fetchingCourses: "Đang tải danh sách lớp...",
    noCourses: "Không tìm thấy lớp học.",
    submitTo: "Nộp",
    loginModalTitle: "Chọn phương thức đăng nhập",
    loginGoogle: "Đăng nhập bằng Google",
    loginGoogleDesc: "Sử dụng tính năng Classroom, Docs, Drive.",
    loginGuest: "Tiếp tục với tư cách Khách",
    loginGuestDesc: "Chỉ lưu lịch sử trên thiết bị này.",
  },
  es: {
    appTitle: "Clase Global",
    subtitle: "Intérprete IA",
    inputLang: "Entrada",
    outputLang: "Salida",
    autoPlay: "Auto Leer",
    playAll: "Reprod. Todo",
    statusListening: "Escuchando...",
    statusStandby: "Toque para iniciar",
    connectionError: "Error",
    retry: "Reintentar",
    connecting: "Conectando...",
    visionButton: "Cámara",
    visionTitle: "Traducción",
    visionDetected: "Detectado",
    visionTranslated: "Traducción",
    visionRetake: "Retomar",
    visionAnalyzing: "Analizando...",
    visionNoText: "Sin texto",
    visionFail: "Fallido",
    visionError: "Error",
    voiceLabel: "Voz",
    emptyHint: "Enciende el micrófono y empieza a hablar.\nTranscribiremos y traduciremos en tiempo real.",
    exportMenu: "Exportar",
    exportDocs: "Guardar en Google Docs",
    exportDrive: "Respaldo en Drive",
    exportClassroom: "Enviar a Classroom",
    loginRequired: "Requiere Google Login",
    loginRequiredDrive: "Login requerido para Drive",
    loginRequiredClassroom: "Login requerido para Classroom",
    loginUnavailable: "Login no disponible (Error de dominio)",
    offlineMode: "No logueado: Descargando archivo de texto.",
    exporting: "Procesando...",
    exportSuccess: "¡Hecho!",
    selectCourse: "Seleccionar clase",
    fetchingCourses: "Obteniendo clases...",
    noCourses: "No se encontraron clases.",
    submitTo: "Enviar",
    loginModalTitle: "Elegir método de inicio",
    loginGoogle: "Iniciar con Google",
    loginGoogleDesc: "Usar funciones de Classroom, Docs y Drive.",
    loginGuest: "Continuar como invitado",
    loginGuestDesc: "Guardar historial solo localmente.",
  }
};

const DEFAULT_TRANS = TRANSLATIONS['en'];
['fr', 'de', 'ru', 'th', 'id', 'ar', 'hi', 'tl', 'mn', 'uz'].forEach(code => {
  if (!TRANSLATIONS[code]) TRANSLATIONS[code] = DEFAULT_TRANS;
});